---
# <--- hugo global configuration --->
markup:
  goldmark:
    renderer:
      unsafe: true

# <--- site specific configuration --->
baseURL: https://geekerhwh.pages.dev/
languageCode: en-us
title: GeekerHWH | Wenhao Hu (胡文昊) | Software Engineer at Meitian | BE AI at Chongqing University
theme: my-hugo-profile # using customized theme istead of original hugo-profile
languages:
  en:
    languageName: English
    languageCode: en
    contentDir: content/en
    flag: flag-us
    weight: 1
  zh:
    languageName: 中文
    languageCode: zh
    contentDir: content/zh
    flag: flag-cn
    weight: 2
taxonomies:
  en_tag: en_tags
  zh_tag: zh_tags
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - RSS
pagination:
  pagerSize: 3
enableRobotsTXT: true
disqusShortname: https-geekerhwh-github-io

Menus:
  main:
    - Dropdown menu: null
    - identifier: Blogs
      title: Blogs languages
      name: Blogs
      weight: 1
    - identifier: en
      title: English blogs
      name: English blogs
      url: /en/blogs/
      parent: Blogs
      weight: 2
    - identifier: zh
      title: 中文博客(不与英文同步)
      name: 中文博客(不与英文同步)
      url: /zh/blogs/
      parent: Blogs
      weight: 3
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    - Dropdown menu: null
    - identifier: more
      title: more
      name: More
      weight: 3
    - identifier: RSS
      title: RSS
      name: RSS
      url: https://geekerhwh.pages.dev/blogs/index.xml
      parent: more
      weight: 1
    - identifier: TG
      title: TG
      name: Telegram
      url: https://t.me/+KmkbQBwj3xdmYWQ1
      parent: more
      weight: 2
    - identifier: Site's updates
      title: Site's updates
      name: Site's updates
      url: https://github.com/Geekerhwh/geekerhwh.github.io
      parent: more
      weight: 3
params:
  title: Wenhao Hu's Site
  description: |
    Hi, my name is Wenhao Hu(胡文昊 in Chinese), Nice to meet you! This is my personal site.
    Hope you can enjoy it.
  staticPath: ""
  favicon: /hashProfile.png
  useBootstrapCDN: false
  mathjax: false
  animate: true
  theme:
    defaultTheme: light
  color:
    textColor: "#343a40"
    secondaryTextColor: "#6c757d"
    backgroundColor: "#eaedf0"
    secondaryBackgroundColor: "#64ffda1a"
    primaryColor: "#007bff"
    secondaryColor: "#f8f9fa"
  # color:
  #   textColor: "#263238"
  #   secondaryTextColor: "#212121"
  #   backgroundColor: "#FFE082"
  #   primaryColor: "#00BFA5"
  #   secondaryColor: "#FFCC80"
  font:
    fontSize: 1.3rem
    fontWeight: 400
    lineHeight: 1.5
    textAlign: left
  navbar:
    align: ms-auto
    brandName: Wenhao Hu's Site
    disableSearch: false
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    menus:
      disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: true
      disableAchievements: false
      disableContact: true
  hero:
    enable: true
    intro: Nice to meet you, my name is
    title: Wenhao Hu
    subtitle: DevOps Engineer at Meituan
    content: >-
      Always be thirsty to touch new things, new peoples, new ideas, new technologies.

    image: /images/gallery/me3.JPG
    bottomImage:
      enable: true
    button:
      enable: false
      name: Resume
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/GeekerHWH
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/wenhao-hu-37565a287/
        - icon: fab fa-telegram
          url: https://t.me/+KmkbQBwj3xdmYWQ1
        - icon: fas fa-rss
          url: https://geekerhwh.pages.dev/blogs/index.xml
  about:
    enable: true
    title: About Me
    image: /images/code.gif
    certifications: >-
      Certifications:
      <br>
      <a href="https://credly.com/badges/a5ba8037-5804-4de6-ac45-f66d818e00cb"><img src="/images/aws-certified-solutions-architect-associate.png" alt="AWS Certified Solutions Architect" class="img-fluid" style="max-width: 100px;"></a>
    
    content: >-
      I am currently a college student at [Chongqing
      University](https://www.cqu.edu.cn/) in Chongqing city, China.


      I know very well the truth of "Talking is cheap, show me your code".

      I'm always eager to get my hands dirty.

      Here are a few Pull Request to Open Source Community:

      - Microsoft/Inshellisense [PR#300](https://github.com/microsoft/inshellisense/pull/330)


      Please feel free to reach out if you are interested in collaborating with me.

    skills:
      enable: true
      title: "Here are a few techs I've been working with recently:"
      items:
        - TiDB
        - Kubernetes
        - Apache Airflow
        - Go & Python & Shell
  techstacks:
    enable: true
    techstack:
      - name: Go
        image: /logos/golang.svg
      - name: Python
        image: /logos/python.svg
      - name: Bash
        image: /logos/bash.svg
      - name: Rust
        image: /logos/rust.svg
      - name: HTML
        image: /logos/html.svg
      - name: CSS
        image: /logos/css.svg
      - name: JavaScript
        image: /logos/javascript.svg
      - name: Hugo
        image: /logos/hugo.svg
      - name: React
        image: /logos/react.svg
      - name: Vue
        image: /logos/vue.svg
      - name: TypeScript
        image: /logos/typescript.svg
      - name: Git
        image: /logos/git.svg
      - name: Docker
        image: /logos/docker.svg
      - name: Podman
        image: /logos/podman.svg
      - name: gRPC
        image: /logos/grpc.svg
      - name: Nginx
        image: /logos/nginx.svg
      - name: Apache HTTP Server
        image: /logos/httpd.svg
      - name: Redis
        image: /logos/redis.svg
      - name: GitHub Actions
        image: /logos/githubactions.svg
      - name: Apache Airflow
        image: /logos/airflow.svg
      - name: Kubernetes
        image: /logos/kubernetes.svg
      - name: Helm
        image: /logos/helm.svg
      - name: ArgoCD
        image: /logos/argocd.svg
      - name: Prometheus
        image: /logos/prometheus.svg
      - name: Grafana
        image: /logos/grafana.svg
      - name: MySQL
        image: /logos/mysql.svg
      - name: MariaDB
        image: /logos/mariadb.svg
      - name: TiDB
        image: /logos/tidb.svg
      - name: OpenStack
        image: /logos/openstack.svg
      - name: AWS
        image: /logos/aws.svg
      - name: Cloudflare
        image: /logos/cloudflare.svg
      - name: Azure
        image: /logos/azure.svg
      - name: Google Cloud Platform
        image: /logos/gcp.svg
      - name: Terraform
        image: /logos/terraform.svg
      - name: Ansible
        image: /logos/ansible.svg
      - name: Hugging Face
        image: /logos/huggingface.svg
      - name: PyTorch
        image: /logos/pytorch.svg
      - name: Vim
        image: /logos/vim.svg
      - name: VSCode
        image: /logos/vscode.svg
      - name: Debian
        image: /logos/debian.svg
      - name: Ubuntu
        image: /logos/ubuntu.svg
      - name: Red Hat
        image: /logos/redhat.svg
      - name: WineHQ
        image: /logos/winehq.svg
      - name: Microsoft Office
        image: /logos/office.svg
      - name: QEMU
        image: /logos/qemu.svg
      - name: VMware
        image: /logos/vmware.svg



  projects:
    enable: true
    items:
      - title: mirrorSpeedTest
        content: >-
          This tool is mainly to help Debian users to select the best apt Repo
          for themselves,

          especially for people who live in China with a special Network Environment, now it

          has supported people all of the world.
        image: /images/projects/debian-wallpaper-1920x1080.jpg
        featured:
          name: Repo Link
          link: https://github.com/GeekerHWH/mirrorSpeedTest
        badges:
          - Go asynchronous programming
          - Debian
          - Docker
          - Github Actions
        links:
          - icon: fab fa-github
            url: https://github.com/GeekerHWH/mirrorSpeedTest
      - title: CustomizeDebian12
        content:
          Quick setup X11 & gnome-core dev desktop environment based on Debian 12
          bookworm. Now it's in progress to support customizing Debian 12 into a local lab in VMs.
        image: /images/projects/bash.jpg
        featured:
          name: Repo Link
          link: https://github.com/GeekerHWH/CustomizeDebian12
        badges:
          - Bash
          - Nvidia-driver
          - KVM
          - WineHQ
          - Docker
        links:
          - icon: fab fa-github
            url: https://github.com/GeekerHWH/CustomizeDebian12
      - title: leetcode-scaffold
        content:
          A scaffold implemented in Rust to generate templates for Unit-Testing, solution note etc.
          It's under deployment right now for personal learning.
        image: /images/projects/leetcode-scaffold.jpg
        featured:
          name: Repo Link
          link: https://github.com/GeekerHWH/leetcode-scaffold
        badges:
          - Rust Learning
          - Leetcode
          - Data Structures and Algorithms
        links:
          - icon: fab fa-github
            url: https://github.com/GeekerHWH/leetcode-scaffold

  experience:
    enable: true
    title: Experience & Certification
    items:
      - job: Blade DevOps & SRE (Intern)
        company: Meituan
        companyUrl: https://www.meituan.com/en-US/about-us
        date: May 2024 - Utill now
        featuredLink:
          enable: false
          name: View the project
          url: https://github.com/GeekerHWH/mirrorSpeedTest
        content: |-
          I was responsible for developing Operator and CI/CD standard pipelines for Blade, which is a Cloud-Native Distributed Database competing with TiDB and OceanBase.
          Also I took part in operation stuffs, deployed different components in Dev, Test cluster environment.
          During my intern career, I learned tons of things like:
          - developing side-car log_collector and webhook in Operator stacks.
          - ArgoCD to support cloud-native CD pipelines.
          - Chaos-Mesh to do a mock failure such as pod pending or network partition
          - Grafana + VictoriaMetrics to monitor information in different cluster.
          - countless SOP (Standard Operation Procedure) and so on......
          

      - job: Backend Developer(Intern)
        company: China Mobile
        companyUrl: https://chinamobileltd.com
        date: Jan 2024 - present
        featuredLink:
          enable: false
          name: View the project
          url: https://github.com/GeekerHWH/mirrorSpeedTest
        content: |-
          Automated data reporting: During the financial audit process, 
          Pyexcel + MySQL + mobile self-developed Panjiang(磐匠) RPA platform
          was used to **automatically download and import financial vouchers into the database,
          process and connect financial report data, and automatically generate daily,
          ten-day, and monthly reports,** replacing the work of approximately 3 financial personnel.

      - job: AWS Certified Solutions Architect - Associtate
        company: AWS
        companyUrl: https://aws.amazon.com/
        date: Nov 2023 - Nov 2026
        featuredLink:
          name: Credly Link
          enable: true
          url: https://www.credly.com/badges/a5ba8037-5804-4de6-ac45-f66d818e00cb
        info:
          enable: true
          content: Validity period
        content: >-
          - Solid Knowledge and skills in compute, networking, storage, and
          database AWS services as well as AWS deployment and management
          services

          - Proficient in Cloud operations and high-availability and high-scalability architecture design knowledge

          - Knowledge and skills in deploying, managing, and operating workloads on AWS as well as implementing security controls and compliance requirements

          - Knowledge and skills in using the AWS Management Console and the AWS Command Line Interface (CLI)Understanding of the AWS Well-Architected Framework, AWS networking, security services, and the AWS global infrastructure

          - Ability to identify which AWS services meet a given technical requirement and to define technical requirements for an AWS-based application
  education:
    enable: true
    index: false
    items:
      - title: International English Language Testing System (IELTS)
        date: 2023 - 2025
        result: Overall 7 (Listening 7.5; Reading 8; Writing 6; Speaking 6)
      - title: Bachelor of Engineering in Artificial Intelligence
        school:
          name: School of Big Data & Software, Chongqing University
          url: https://www.cse.cqu.edu.cn/
        date: 2021 - 2025
        score: 82.59(Top 20%)
        content: >-
          <details>
            <summary>Click to see professional courses in my Uni</summary>

            - Data Structures & Algorithms (in C)
            - Database Principles and Design(MySQL)
            - Operating System
            - Computer Network
            - Software Engineering
            - Information Security
            - Human-Computer Interaction (HCI) Design
            - Machine Learning
            - Deep Learning
            - Computer Vision
            - Natural Language Processing
          </details>

           2023.07-present: Served as team leader in the first Chongqing University
          Student Innovation Training Project (Research Project on Controlled Text 

          Generation Methods under Hard Constraints), responsible for NLP model construction, deployment, 

          and testing, and also responsible for project establishment/mid-term/final debates
        featuredLink:
          enable: false
          name: My academic record
          url: https://example.com
  achievements:
    enable: false
    items:
      - title: First Prize in China Youth Photography Competition
        content: CyberChongQing is the first impression of this city
        url: https://geekerhwh.pages.dev/gallery/
      - title:
          Admitted to China's 985 University in one fell swoop in the college
          entrance examination
        content: >-
          The 985 Program is an elite education program for China’s Top 1%.

          It aims to cultivate talents who will make outstanding contributions to top careers in the new era.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: https://github.com/gurusabarish/hugo-profile
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
  contact:
    enable: true
    content: >-
      My inbox is always open. Whether you have a question or just want to
      say hi, 

      I'll try my best to get back to you!
    email: hacker.huwenhao@gmail.com
    btnName: Mail me
  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/GeekerHWH
      linkedin: https://www.linkedin.com/in/wenhao-hu-37565a287/
      telegram: https://t.me/+KmkbQBwj3xdmYWQ1
      rss: https://geekerhwh.pages.dev/blogs/index.xml
  listPages:
    disableFeaturedImage: false
  singlePages:
    readTime:
      enable: true
      content: min read
    scrollprogress:
      enable: true
  terms:
    read: Read
    toc: Table Of Contents
    copyright: All rights reserved
    pageNotFound: Page not found
    emailText: Check out this site
  datesFormat:
    article: Jan 2, 2006
    articleList: Jan 2, 2006
    articleRecent: Jan 2, 2006
